# Generated by Django 5.2.17 on 2026-10-05 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('PYTHON', 'Python'), ('DJANGO', 'Django'), ('SQL', 'SQL'), ('JS', 'JavaScript'), ('HTML_CSS', 'HTML / CSS')], max_length=100)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='EnseignantReferent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('sexe', models.CharField(choices=[('F', 'f'), ('H', 'h')])),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
                'ordering': ['nom', 'prenom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('ville', models.CharField(max_length=80)),
                ('secteur', models.CharField(max_length=80)),
                ('contact', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'entreprise',
                'verbose_name_plural': 'entreprises',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('sexe', models.CharField(choices=[('F', 'f'), ('H', 'h')])),
                ('matricule', models.CharField(max_length=50)),
                ('promotion', models.CharField(max_length=30)),
                ('competences', models.ManyToManyField(related_name='etudiants', to='stages.competence')),
            ],
            options={
                'ordering': ['promotion'],
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nb_place', models.PositiveIntegerField()),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offres', to='stages.entreprise')),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
        migrations.AddField(
            model_name='competence',
            name='offres',
            field=models.ManyToManyField(related_name='competences', to='stages.offre'),
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depot', models.DateField()),
                ('statut', models.CharField(choices=[('depose', 'DEPOSE'), ('retenue', 'RETENUE'), ('refuse', 'REFUSE')])),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidature', to='stages.etudiant')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='stages.offre')),
            ],
            options={
                'ordering': ['date_depot'],
            },
        ),
        migrations.CreateModel(
            name='TuteurEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('sexe', models.CharField(choices=[('F', 'f'), ('H', 'h')])),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise', to='stages.entreprise')),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
                'ordering': ['nom', 'prenom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.TextField(max_length=255)),
                ('candidature', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stage', to='stages.candidature')),
                ('enseignant_referent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='stages.enseignantreferent')),
                ('tuteur_entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='stages.tuteurentreprise')),
            ],
        ),
        migrations.AddConstraint(
            model_name='candidature',
            constraint=models.UniqueConstraint(fields=('offre', 'etudiant'), name='offre_etudiant'),
        ),
    ]
