# Generated by Django 5.2.17 on 2026-09-30 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_personne'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personne',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Personne', 'verbose_name_plural': 'Personnes'},
        ),
    ]
