# Generated by Django 5.2.17 on 2026-09-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0007_tuteurentreprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
    ]
