# Generated by Django 5.2.17 on 2026-09-30 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0008_offre'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnseignantReferent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='competence',
            name='competences',
            field=models.ManyToManyField(related_name='offres', to='stages.offre'),
        ),
        migrations.AddField(
            model_name='offre',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offres', to='stages.entreprise'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='competences',
            field=models.ManyToManyField(related_name='etudiants', to='stages.competence'),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.TextField(max_length=255)),
                ('enseignant_referent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='stages.enseignantreferent')),
                ('tuteur_entreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='stages.tuteurentreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nb_place', models.PositiveIntegerField()),
                ('date_depot', models.DateField()),
                ('statut', models.CharField(choices=[('depose', 'DEPOSE'), ('retenue', 'RETENUE'), ('refuse', 'REFUSE')])),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidature', to='stages.etudiant')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='stages.offre')),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='candidature', to='stages.stage')),
            ],
            options={
                'ordering': ['date_debut'],
            },
        ),
    ]
