# Generated by Django 5.2.17 on 2026-09-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0009_enseignantreferent_competence_competences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='competences',
        ),
        migrations.AddField(
            model_name='competence',
            name='offres',
            field=models.ManyToManyField(related_name='competences', to='stages.offre'),
        ),
    ]
